-- 모든 데이터가 날아가니 주의하세요.

DROP TABLE IF EXISTS `STORE_INVOICE`;
DROP TABLE IF EXISTS `STORE_ORDER`;
DROP TABLE IF EXISTS `STORE_CASHBOOK`;
DROP TABLE IF EXISTS `STORE_RESERVATION`;
DROP TABLE IF EXISTS `STORE_TABLE`;
DROP TABLE IF EXISTS `STORE_CATEGORY`;
DROP TABLE IF EXISTS `STORE_ACCOUNT`;

DROP TABLE IF EXISTS `SERVICE_STORE`;
DROP TABLE IF EXISTS `SERVICE_FILE`;
DROP TABLE IF EXISTS `SERVICE_BOARD`;
DROP TABLE IF EXISTS `SERVICE_ACCOUNT`;

CREATE TABLE `SERVICE_ACCOUNT` (
	`SERVICE_ID`	VARCHAR(20)	PRIMARY KEY,
	`SERVICE_EMAIL`	VARCHAR(50)	NOT NULL,
	`SERVICE_PW` VARCHAR(20) NOT NULL,
	`SERVICE_TYPE` CHAR(2) NOT NULL DEFAULT 'U',
	`REGDATE`	DATE NOT NULL,
	`DELFLAG`	CHAR(2) NOT NULL DEFAULT 'N'
);

CREATE TABLE `SERVICE_BOARD` (
	`BOARD_SEQ`	INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`SERVICE_ID` VARCHAR(20) NOT NULL,
	`READCOUNT`	INTEGER	NOT NULL DEFAULT 0,
	`REGDATE` DATE NOT NULL,
	`TITLE`	VARCHAR(50)	NOT NULL,
	`CONTENT`	VARCHAR(4000)	NOT NULL,
	`REF`	INTEGER NOT NULL,
	`STEP`	INTEGER	NOT NULL,
	`DEPTH`	INTEGER	NOT NULL,
	`TYPE`	CHAR NOT NULL	DEFAULT 'Q',
	`DELFLAG`	CHAR NOT NULL DEFAULT 'N',
	CONSTRAINT SERVICE_ID_FK FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE_ACCOUNT (SERVICE_ID) ON DELETE RESTRICT
);

CREATE TABLE `SERVICE_FILE` (
	`FILE_SEQ`	INTEGER	AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`BOARD_SEQ`	INTEGER	NOT NULL,
	`ORIGIN_FNAME` VARCHAR(500) NOT NULL,
	`STORED_FNAME` VARCHAR(500)	NOT NULL,
	`FILE_SIZE`	INTEGER	NOT NULL,
	`REGDATE`	DATE NOT NULL,
	`DELFLAG`	CHAR NOT NULL DEFAULT 'N',
	CONSTRAINT SERVICE_FILE_FK FOREIGN KEY (BOARD_SEQ) REFERENCES SERVICE_BOARD (BOARD_SEQ) ON DELETE RESTRICT
);

CREATE TABLE `SERVICE_STORE` (
	`STORE_SEQ`	INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`SERVICE_ID` VARCHAR(20) NOT NULL,
	`STORE_NAME` VARCHAR(50) NOT NULL,
	`STORE_DETAIL` VARCHAR(4000) NOT NULL,
	`STORE_TYPE`	VARCHAR(30)	NOT NULL,
	`STORE_ADDRESS`	VARCHAR(200) NOT NULL,
	`STORE_TEL`	VARCHAR(20)	NOT NULL,
	`STORE_HOUR` VARCHAR(50) NOT NULL,
	`DELFLAG`	CHAR(2) NOT NULL DEFAULT 'N',
	CONSTRAINT SERVICE_STORE_FK FOREIGN KEY (SERVICE_ID) REFERENCES  SERVICE_ACCOUNT (SERVICE_ID) ON DELETE RESTRICT
);


CREATE TABLE `STORE_ACCOUNT` (
	`USER_ID`	VARCHAR(20)	PRIMARY KEY NOT NULL,
	`SERVICE_ID` VARCHAR(20) NOT NULL,
	`USER_EMAIL` VARCHAR(50) NOT NULL,
	`USER_PW`	VARCHAR(20)	NOT NULL,
	`USER_TYPE` CHAR(2)	NOT NULL DEFAULT 'C',
	`USER_REGDATE` DATE NOT NULL,
	`POINT`	INTEGER NOT	NULL DEFAULT 0,
	`DELFLAG` CHAR(2) NOT NULL	DEFAULT 'U',
	CONSTRAINT `SERVICE_ACCOUNT_USER_ID_FK` FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE_ACCOUNT (SERVICE_ID) ON DELETE RESTRICT
);

CREATE TABLE `STORE_CATEGORY`(
   `MENU_SEQ` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `STORE_SEQ` INTEGER NOT NULL,
   `MENU_NAME` VARCHAR(20) NOT NULL,
   `CATEG_NAME` VARCHAR(20) NOT NULL,
   `MENU_INFO` VARCHAR(50) NOT NULL,
   `ORIGIN_FNAME` VARCHAR(2000) NOT NULL,
   `STORED_FNAME` VARCHAR(2000) NOT NULL,
   `MENU_PRICE` INTEGER NOT NULL DEFAULT 0,
   `DELFLAG` CHAR(2) NOT NULL DEFAULT 'N',
   CONSTRAINT `STORE_CATEGORY_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES  SERVICE_STORE (STORE_SEQ) ON DELETE RESTRICT
);

CREATE TABLE `STORE_TABLE` (
	`TABLE_SEQ`	INTEGER	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`STORE_SEQ`	INTEGER	NOT NULL,
	`TABLE_NAME` VARCHAR(20)	NOT NULL,
	`RESERVATION` CHAR(2) NOT NULL DEFAULT 'D',
	`MIN_PEOPLE` INTEGER NOT NULL DEFAULT 1,
	`MAX_PEOPLE`	INTEGER	NOT NULL,
	`DELFLAG` CHAR(2) NOT NULL DEFAULT 'N',
	CONSTRAINT `STORE_TABLE_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES SERVICE_STORE (STORE_SEQ) ON DELETE RESTRICT
);

CREATE TABLE `STORE_RESERVATION` (
	`RESERV_SEQ` INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`STORE_SEQ` INTEGER NOT NULL,
	`TABLE_SEQ` INTEGER NOT NULL,
	`USER_ID` VARCHAR(20) NOT NULL,
	`RESERV_TIME`	TIMESTAMP NOT NULL,
	`RESERV_PEOPLE`	INTEGER	NOT NULL,
	`DELFLAG`	CHAR(2) NOT NULL DEFAULT 'N',
	CONSTRAINT `STORE_RESERVATION_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES `STORE_TABLE` (STORE_SEQ) ON DELETE RESTRICT ,
	CONSTRAINT `STORE_RESERVATION_TABLE_SEQ_FK` FOREIGN KEY (TABLE_SEQ) REFERENCES `STORE_TABLE` (TABLE_SEQ) ON DELETE RESTRICT,
	CONSTRAINT `STORE_RESERVATION_USER_ID_FK` FOREIGN KEY (USER_ID) REFERENCES `STORE_ACCOUNT` (USER_ID) ON DELETE RESTRICT
);

CREATE TABLE `STORE_CASHBOOK` (
  `CASH_SEQ` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `STORE_SEQ`	INTEGER NOT NULL,
  `CASH_DATE`	TIMESTAMP NOT NULL,
  `CASH_DEPOSIT` INTEGER NULL,
  `CASH_WITHDRAW` INTEGER NULL,
  `CASH_BALANCE` INTEGER NOT NULL DEFAULT '0',
  CONSTRAINT `STORE_CASHBOOK_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES SERVICE_STORE (STORE_SEQ) ON DELETE RESTRICT
);

CREATE TABLE `STORE_ORDER` (
   `ORDER_SEQ` INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
   `STORE_SEQ` INTEGER NOT NULL,
   `TABLE_SEQ` INTEGER NOT NULL,
   `MENU_SEQ` INTEGER NOT NULL,
   `MAKE` CHAR(2) NOT NULL DEFAULT 'N',
   `ORDER_DATE` TIMESTAMP NOT NULL,
   `MENU_PRICE` INTEGER NOT NULL,
   `DELFLAG` CHAR(2) NOT NULL,
   CONSTRAINT `STORE_ORDER_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES `STORE_TABLE` (STORE_SEQ) ON DELETE RESTRICT,
   CONSTRAINT `STORE_ORDER_TABLE_SEQ_FK` FOREIGN KEY (TABLE_SEQ) REFERENCES `STORE_TABLE` (TABLE_SEQ) ON DELETE RESTRICT,
   CONSTRAINT `STORE_ORDER_MENU_SEQ_FK` FOREIGN KEY (MENU_SEQ) REFERENCES `STORE_CATEGORY` (MENU_SEQ) ON DELETE RESTRICT
);

CREATE TABLE `STORE_INVOICE` (
   `INVOICE_SEQ` INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
   `STORE_SEQ` INTEGER NOT NULL,
   `TABLE_SEQ` INTEGER NOT NULL,
   `MENU_AMOUNT`	INTEGER NOT NULL,
   `TAX_AMOUNT`	INTEGER NOT NULL,
   `TOTAL_AMOUNT`	INTEGER NOT NULL,
   `DISCOUNT_AMOUNT`	INTEGER NOT NULL,
   `FINAL_AMOUNT`	INTEGER NOT NULL,
   `PAID_DATE` TIMESTAMP NOT NULL,
   `PAYMENT_METHOD` VARCHAR(20) NOT NULL,
	 `DELFLAG`	CHAR(2) NOT NULL DEFAULT 'N',
	CONSTRAINT `STORE_INVOICE_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES  `STORE_ORDER` (STORE_SEQ) ON DELETE RESTRICT,
	CONSTRAINT `STORE_INVOICE_TABLE_SEQ_FK` FOREIGN KEY (TABLE_SEQ) REFERENCES  `STORE_ORDER` (TABLE_SEQ) ON DELETE RESTRICT
);


COMMIT;