
DROP TABLE IF EXISTS `STORE_(hello)_(2)_ORDER`;
DROP TABLE IF EXISTS `STORE_(hello)_(2)_INVOICE`;
DROP TABLE IF EXISTS `STORE_(hello)_(2)_CASHBOOK`;
DROP TABLE IF EXISTS `STORE_(hello)_(2)_RESERVATION`;
DROP TABLE IF EXISTS `STORE_(hello)_(2)_TABLE`;
DROP TABLE IF EXISTS `STORE_(hello)_(2)_CATEGORY`;
DROP TABLE IF EXISTS `STORE_(hello)_ACCOUNT`;

DROP TABLE IF EXISTS `STORE_(winetree)_(1)_ORDER`;
DROP TABLE IF EXISTS `STORE_(winetree)_(1)_INVOICE`;
DROP TABLE IF EXISTS `STORE_(winetree)_(1)_CASHBOOK`;
DROP TABLE IF EXISTS `STORE_(winetree)_(1)_RESERVATION`;
DROP TABLE IF EXISTS `STORE_(winetree)_(1)_TABLE`;
DROP TABLE IF EXISTS `STORE_(winetree)_(1)_CATEGORY`;
DROP TABLE IF EXISTS `STORE_(winetree)_ACCOUNT`;

DROP TABLE IF EXISTS `STORE_(SERVICE_ID)_(STORE_SEQ)_ORDER`;
DROP TABLE IF EXISTS `STORE_(SERVICE_ID)_(STORE_SEQ)_INVOICE`;
DROP TABLE IF EXISTS `STORE_(SERVICE_ID)_(STORE_SEQ)_CASHBOOK`;
DROP TABLE IF EXISTS `STORE_(SERVICE_ID)_(SERVICE_SEQ)_RESERVATION`;
DROP TABLE IF EXISTS `STORE_(SERVICE_ID)_(STORE_SEQ)_TABLE`;
DROP TABLE IF EXISTS `STORE_(SERVICE_ID)_(STORE_SEQ)_CATEGORY`;
DROP TABLE IF EXISTS `STORE_(SERVICE_ID)_ACCOUNT`;
DROP TABLE IF EXISTS `SERVICE_STORE`;
DROP TABLE IF EXISTS `SERVICE_FILE`;
DROP TABLE IF EXISTS `SERVICE_BOARD`;
DROP TABLE IF EXISTS `SERVICE_ACCOUNT`;

CREATE TABLE `SERVICE_ACCOUNT` (
	`SERVICE_ID`	VARCHAR(20)	PRIMARY KEY,
	`SERVICE_EMAIL`	VARCHAR(50)	NOT NULL,
	`SERVICE_PW` VARCHAR(20) NOT NULL,
	`SERVICE_TYPE` CHAR(2) NOT NULL DEFAULT 'U',
	`REGDATE`	DATE NOT NULL,
	`DELFLAG`	CHAR(2) NOT NULL DEFAULT 'N'
);

CREATE TABLE `SERVICE_BOARD` (
	`BOARD_SEQ`	INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`SERVICE_ID` VARCHAR(20) NOT NULL,
	`READCOUNT`	INTEGER	NOT NULL DEFAULT 0,
	`REGDATE` DATE NOT NULL,
	`TITLE`	VARCHAR(50)	NOT NULL,
	`CONTENT`	VARCHAR(4000)	NOT NULL,
	`REF`	INTEGER NOT NULL,
	`STEP`	INTEGER	NOT NULL,
	`DEPTH`	INTEGER	NOT NULL,
	`TYPE`	CHAR NOT NULL	DEFAULT 'Q',
	`DELFLAG`	CHAR NOT NULL DEFAULT 'N',
	CONSTRAINT SERVICE_ID_FK FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE_ACCOUNT (SERVICE_ID) ON DELETE RESTRICT
);

CREATE TABLE `SERVICE_FILE` (
	`FILE_SEQ`	INTEGER	AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`BOARD_SEQ`	INTEGER	NOT NULL,
	`ORIGIN_FNAME` VARCHAR(500) NOT NULL,
	`STORED_FNAME` VARCHAR(500)	NOT NULL,
	`FILE_SIZE`	INTEGER	NOT NULL,
	`REGDATE`	DATE NOT NULL,
	`DELFLAG`	CHAR NOT NULL DEFAULT 'N',
	CONSTRAINT SERVICE_FILE_FK FOREIGN KEY (BOARD_SEQ) REFERENCES SERVICE_BOARD (BOARD_SEQ) ON DELETE RESTRICT
);

CREATE TABLE `SERVICE_STORE` (
	`STORE_SEQ`	INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`SERVICE_ID` VARCHAR(20) NOT NULL,
	`STORE_NAME` VARCHAR(50) NOT NULL,
	`STORE_DETAIL` VARCHAR(4000) NOT NULL,
	`STORE_TYPE`	VARCHAR(30)	NOT NULL,
	`STORE_ADDRESS`	VARCHAR(200) NOT NULL,
	`STORE_TEL`	VARCHAR(20)	NOT NULL,
	`STORE_HOUR` VARCHAR(50) NOT NULL,
	`DELFLAG`	CHAR(2) NOT NULL DEFAULT 'N',
	CONSTRAINT SERVICE_STORE_FK FOREIGN KEY (SERVICE_ID) REFERENCES  SERVICE_ACCOUNT (SERVICE_ID) ON DELETE RESTRICT
);

COMMIT;