INSERT INTO SERVICE_ACCOUNT(SERVICE_ID, SERVICE_EMAIL, SERVICE_PW, REGDATE) VALUES(
  'winetree', 'winetreee@gmail.com', 'winetree', now()
);

INSERT INTO SERVICE_BOARD(SERVICE_ID, REGDATE, TITLE, CONTENT, REF, STEP, DEPTH) VALUES (
  'winetree', now(), 'title', 'content', 0,0,0
);

INSERT INTO SERVICE_FILE(BOARD_SEQ, ORIGIN_FNAME, STORED_FNAME, FILE_SIZE, REGDATE) VALUES (
  1, 'ORIGIN_FNAME', 'STORED_FNAME', 35342, NOW()
);

INSERT INTO SERVICE_STORE(STORE_SEQ, SERVICE_ID, STORE_NAME, STORE_DETAIL, STORE_TYPE, STORE_ADDRESS, STORE_TEL, STORE_HOUR) VALUES (
  1, 'winetree', '매장 이름', '매장 설명', '업종', '매장의 주소', '매장 전화번호', '영업시간 안내'
);

INSERT INTO SERVICE_ACCOUNT(SERVICE_ID, SERVICE_EMAIL, SERVICE_PW, REGDATE) VALUES(
  'hello', 'hello@gmail.com', 'hello', now()
);

INSERT INTO SERVICE_BOARD(SERVICE_ID, REGDATE, TITLE, CONTENT, REF, STEP, DEPTH) VALUES (
  'hello', now(), 'title', 'content', 0,0,0
);

INSERT INTO SERVICE_FILE(BOARD_SEQ, ORIGIN_FNAME, STORED_FNAME, FILE_SIZE, REGDATE) VALUES (
  1, 'ORIGIN_FNAME', 'STORED_FNAME', 35342, NOW()
);

INSERT INTO SERVICE_STORE(STORE_SEQ, SERVICE_ID, STORE_NAME, STORE_DETAIL, STORE_TYPE, STORE_ADDRESS, STORE_TEL, STORE_HOUR) VALUES (
  2, 'hello', '매장 이름', '매장 설명', '업종', '매장의 주소', '매장 전화번호', '영업시간 안내'
);

COMMIT;