
CREATE TABLE `STORE_ACCOUNT` (
	`USER_ID`	VARCHAR(20)	PRIMARY KEY NOT NULL,
	`SERVICE_ID` VARCHAR(20) NOT NULL,
	`USER_EMAIL` VARCHAR(50) NOT NULL,
	`USER_PW`	VARCHAR(20)	NOT NULL,
	`USER_TYPE` CHAR(2)	NOT NULL DEFAULT 'C',
	`USER_REGDATE` DATE NOT NULL,
	`POINT`	INTEGER NOT	NULL DEFAULT 0,
	`DELFLAG` CHAR(2) NOT NULL	DEFAULT 'U',
	CONSTRAINT `SERVICE_ACCOUNT_USER_ID_FK` FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE_ACCOUNT (SERVICE_ID) ON DELETE RESTRICT
);

CREATE TABLE `STORE_CATEGORY`(
   `MENU_SEQ` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `MENU_NAME` VARCHAR(20) NOT NULL,
   `CATEG_NAME` VARCHAR(20) NOT NULL,
   `MENU_INFO` VARCHAR(50) NOT NULL,
   `ORIGIN_FNAME` VARCHAR(2000) NOT NULL,
   `STORED_FNAME` VARCHAR(2000) NOT NULL,
   `MENU_PRICE` INTEGER NOT NULL DEFAULT 0,
   `DELFLAG` CHAR(2) NOT NULL DEFAULT 'N'
);

CREATE TABLE `STORE_TABLE` (
	`TABLE_SEQ`	INTEGER	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`STORE_SEQ`	INTEGER	NOT NULL,
	`TABLE_NAME` VARCHAR(20)	NOT NULL,
	`RESERVATION` CHAR(2) NOT NULL DEFAULT 'D',
	`MIN_PEOPLE` INTEGER NOT NULL DEFAULT 1,
	`MAX_PEOPLE`	INTEGER	NOT NULL,
	`DELFLAG` CHAR(2) NOT NULL DEFAULT 'N',
	CONSTRAINT `STORE_TABLE_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES SERVICE_STORE (STORE_SEQ) ON DELETE RESTRICT
);

CREATE TABLE `STORE_RESERVATION` (
	`RESERV_SEQ` INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`STORE_SEQ` INTEGER NOT NULL,
	`TABLE_SEQ` INTEGER NOT NULL,
	`USER_ID` VARCHAR(20) NOT NULL,
	`RESERV_TIME`	TIMESTAMP NOT NULL,
	`RESERV_PEOPLE`	INTEGER	NOT NULL,
	`DELFLAG`	CHAR(2) NOT NULL DEFAULT 'N',
	CONSTRAINT `STORE_RESERVATION_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES SERVICE_STORE (STORE_SEQ) ON DELETE RESTRICT ,
	CONSTRAINT `STORE_RESERVATION_TABLE_SEQ_FK` FOREIGN KEY (TABLE_SEQ) REFERENCES `STORE_TABLE` (TABLE_SEQ) ON DELETE RESTRICT,
	CONSTRAINT `STORE_RESERVATION_USER_ID_FK` FOREIGN KEY (USER_ID) REFERENCES `STORE_ACCOUNT` (USER_ID) ON DELETE RESTRICT
);

CREATE TABLE `STORE_CASHBOOK` (
  `STORE_SEQ`	INTEGER NOT NULL,
  `CASH_DATE`	TIMESTAMP NOT NULL,
  `CASH_DEPOSIT` INTEGER NULL,
  `CASH_WITHDRAW` INTEGER NULL,
  `CASH_BALANCE` INTEGER NOT NULL DEFAULT '0',
  CONSTRAINT `STORE_CASHBOOK_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES SERVICE_STORE (STORE_SEQ) ON DELETE RESTRICT
);

CREATE TABLE `STORE_INVOICE` (
   `INVOICE_SEQ` INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
   `TABLE_SEQ` INTEGER NOT NULL,
   `STORE_SEQ`	INTEGER NOT NULL,
   `MENU_AMOUNT`	INTEGER NOT NULL,
   `TAX_AMOUNT`	INTEGER NOT NULL,
   `TOTAL_AMOUNT`	INTEGER NOT NULL,
   `DISCOUNT_AMOUNT`	INTEGER NOT NULL,
   `FINAL_AMOUNT`	INTEGER NOT NULL,
   `PAID_DATE` TIMESTAMP NOT NULL,
   `PAYMENT_METHOD` VARCHAR(20) NOT NULL,
	 `DELFLAG`	CHAR(2) NOT NULL DEFAULT 'N',
  CONSTRAINT `STORE_INVOICE_STORE_SEQ_FK` FOREIGN KEY (STORE_SEQ) REFERENCES  `STORE_TABLE` (STORE_SEQ) ON DELETE RESTRICT,
	CONSTRAINT `STORE_INVOICE_TABLE_SEQ_FK` FOREIGN KEY (TABLE_SEQ) REFERENCES  `STORE_TABLE` (TABLE_SEQ) ON DELETE RESTRICT
);

CREATE TABLE `STORE_ORDER` (
   `ORDER_SEQ` INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
   `INVOICE_SEQ` INTEGER NOT NULL,
   `MENU_SEQ` INTEGER NOT NULL,
   `PAID_DATE` TIMESTAMP NOT NULL,
   `MENU_PRICE` INTEGER NOT NULL,
   CONSTRAINT `STORE_ORDER_INVOICE_SEQ_FK` FOREIGN KEY (INVOICE_SEQ) REFERENCES `STORE_INVOICE` (INVOICE_SEQ) ON DELETE RESTRICT,
   CONSTRAINT `STORE_ORDER_MENU_SEQ_FK` FOREIGN KEY (MENU_SEQ) REFERENCES `STORE_CATEGORY` (MENU_SEQ) ON DELETE RESTRICT
);

COMMIT;