CREATE TABLE `SERVICE_STORE` (
	`STORE_SEQ`	INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`SERVICE_ID` VARCHAR(20) NOT NULL,
	`STORE_NAME` VARCHAR(50) NOT NULL,
	`STORE_DETAIL` VARCHAR(4000) NOT NULL,
	`STORE_TYPE`	VARCHAR(30)	NOT NULL,
	`STORE_ADDRESS`	VARCHAR(200) NOT NULL,
	`STORE_TEL`	VARCHAR(20)	NOT NULL,
	`STORE_HOUR` VARCHAR(50) NOT NULL,
	`DELFLAG`	CHAR(2) NOT NULL DEFAULT 'N',
	CONSTRAINT SERVICE_STORE_FK FOREIGN KEY (SERVICE_ID) REFERENCES  SERVICE_ACCOUNT (SERVICE_ID) ON DELETE RESTRICT
);


--- 전체 매장 목록 조회 기능

SELECT STORE_SEQ, SERVICE_ID, STORE_NAME, STORE_DETAIL, STORE_TYPE, STORE_ADDRESS, STORE_TEL, STORE_HOUR, DELFLAG FROM SERVICE_STORE;

-- 특정 세부 매장 조회 기능

SELECT STORE_SEQ, SERVICE_ID, STORE_NAME, STORE_DETAIL, STORE_TYPE, STORE_ADDRESS, STORE_TEL, STORE_HOUR, DELFLAG FROM SERVICE_STORE WHERE STORE_SEQ = #{store_seq};

-- 신규 매장 추가 기능

INSERT INTO SERVICE_STORE(SERVICE_ID, STORE_NAME, STORE_DETAIL, STORE_TYPE, STORE_ADDRESS, STORE_TEL, STORE_HOUR) VALUES (
  #{service_id}, #{store_name}, #{store_detail}, {store_type}, #{store_address}, #{store_tel}, #{store_hour});

-- 매장 수정 기능

UPDATE SERVICE_STORE SET STORE_NAME = #{store_name}, STORE_DETAIL = #{store_detail}, STORE_TYPE = #{store_type}, STORE_ADDRESS = #{store_address}, STORE_TEL = #{store_tel}, STORE_HOUR = #{store_hour} WHERE STORE_SEQ = #{store_seq};


-- 매장 삭제 기능

UPDATE SERVICE_STORE SET DELFLAG = 'Y' WHERE STORE_SEQ = #{store_seq};

-- 매장 전체 삭제 기능

UPDATE SERVICE_STORE SET DELFLAG = 'Y';